projects/mef.md, projects/owin-authentication-middleware.md
Reviewing the project pages, found a few minor updates needed to Katana and MEF
=> Minor updates

projects/orchard.md
=> New code location

projects/llilc.md, projects/projects.json
Creating a new project page for LLILC
=> Add LLILC project page

README.md, projects/WorldWideTelescope.md, projects/projects.json
Adding project information for WWT /cc @doctorspaceman + @kfogel
=> Add WorldWide Telescope

README.md, projects/open-live-writer.md, projects/projects.json
Add the Open Live Writer project
@RobDolin can you take a quick look and suggest any edits?
=> Add Open Live Writer

projects/mailkit.md, projects/mimekit.md
Fixed up MimeKit and MailKit links.
=> Updated mimekit.md and mailkit.md

guidance/be-nice.md, guidance/new-projects.md, guidance/readme-guide.md, guidance/repo-guide.md
I did, however, preserve the Queen's English spellings in the original
text.
=> Proofread and fix a few typos.

projects/aspnet-ajax.md
Updated the description to mention DevExpress. Updated the links to current project on github. Added 2 main project managers from DevExpress.
=> Updated aspnet-ajax.md

README.md, projects/cake.md, projects/projects.json
This will add Cake to the list of projects.
=> Add Cake to list of projects

README.md, projects/projects.json, projects/reactive-extensions.md
Used #44 as an example, I think that's covered everything...
=> add Rx.NET into project listings

guidance/new-projects.md, projects/NETCore.md
Add link to logos, and recommendation on linking to images for new projects.
=> Guidance for project links

projects/orchard.md
Fix about link url and replace JabbR by Gitter.
=> Change project Orchard

README.md, projects/peachpie.md, projects/projects.json
Created peachpie.md
Added Peachpie to projects.json
Added Peachpie to Readme.md
=> Add Peachpie to project list

README.md, projects/sourcelink.md
Adding SourceLink to the project list as per the checklist https://github.com/ctaggart/SourceLink/issues/138
=> add SourceLink

projects/humanizer.md, projects/projects.json
Onboarding Humanizer: https://github.com/Humanizr/Humanizer/issues/682
=> Add Humanizer

README.md
=> Add ML.NET to readme

README.md, projects/projects.json, projects/steeltoe.md
Hi @jongalloway, Here is the PR for adding Steeltoe to the projects listing.  Let me know if you need any changes. 
Thanks.
=> Add Steeltoe to the project listing

README.md, projects/newtonsoft.json.md
=> Add Newtonsoft.Json

projects/projects.json
Fixes dotnet/dotnetfoundation-website#72
Fixes #125
=> Update MVVM project logo

projects/projects.json
=> adds the prism logo

projects/projects.json
=> adds Umbraco logo

projects/NETCore.md, projects/dotnet-compiler-platform.md
/cc @mairaw @scottaddie
Maira, did I miss any project repos to tag?
=> add links to .NET docs

projects/aspnet-core.md
Provide a link to the docs site for ASP.NET Core.
=> Add link to ASP.NET Core docs

projects/NETCore.md
@BillWagner should we add the samples project too?
=> add docs samples link

README.md, projects/dotvvm.md, projects/projects.json
=> Add DotVVM

projects/mlnet.md
/cc @JRAlexander @shauheen 
To match the info we have added for other projects
=> add links to ML.NET docs

README.md, projects/anglesharp.md, projects/projects.json
=> Add AngleSharp

projects/dnn-platform.md
Edits to reflect changes in repository structure with recent modifications to the overall project structure.
=> Edits to DNN Platform Information

projects/cake.md
@jongalloway just noticed that this wasn't up to date.
=> Update Cake Project Contacts

projects/reactiveui.md
Fixes https://github.com/dotnet-foundation/dotnetfoundation-website/issues/68
=> Update RxUI license to reflect repo

governance/foundation-structure.md
Was `https://dotnetfoundation.org/team` but now is `https://dotnetfoundation.org/about#team`
=> Update Teams Link

README.md, projects/nuget-trends.md, projects/projects.json
Adding NuGet Trends.
/cc @clairernovotny, @joaopgrassi
=> add NuGet Trends

README.md, projects/FluentValidation.md, projects/projects.json
As per https://github.com/dotnet-foundation/projects/issues/27
=> Adds FluentValidation to the project list

README.md, projects/corewf.md, projects/projects.json
Fixes https://github.com/UiPath-Open/corewf/issues/95
=> Add CoreWF to projects list

README.md, projects/avalonia.md, projects/projects.json
=> Add Avalonia

projects/prism.md
Various updates for out of date links, License reference and project contacts
=> update for Prism contacts / links
